steps:
  - name: 'docker/compose:1.27.4'
    id: Build App Images
    args: ['-f', 'docker-compose.prod-build.yml', 'build', '--parallel']

  - name: 'docker/compose:1.27.4'
    id: Push App Images
    args: [ '-f', 'docker-compose.prod-build.yml', 'push']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy App
    entrypoint: /bin/bash
    args:
    - '-c'
    - |
      sh cicd/cloudbuild.sh || exit $?
    
images:
  - 'asia-south1-docker.pkg.dev/lbg-cloudathon-iam-innovators/iam-innovators/frontend:latest'
  - 'asia-south1-docker.pkg.dev/lbg-cloudathon-iam-innovators/iam-innovators/backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY