services:
  client:
    image: asia-south1-docker.pkg.dev/ltc-hack-prj-21/iam-innovators/frontend:latest
    build:
      dockerfile: Dockerfile
      context: ./backend
    networks:
      - ts-network
  server:
    image: asia-south1-docker.pkg.dev/ltc-hack-prj-21/iam-innovators/backend:latest
    build:
      dockerfile: Dockerfile
      context: ./frontend
    networks:
      - ts-network

networks:
  ts-network:
    driver: bridge
    