services:
  client:
    image: asia-south1-docker.pkg.dev/lbg-cloudathon-iam-innovators/iam-innovators/frontend:latest
    ports:
      - 80:3000
    networks:
      - ts-network
    environment:
      - API_URL=http://35.188.50.151:81/
      - REACT_APP_API_URL=http://35.188.50.151:81/
  server:
    image: asia-south1-docker.pkg.dev/lbg-cloudathon-iam-innovators/iam-innovators/backend:latest
    ports:
      - 81:5400
    networks:
      - ts-network

networks:
  ts-network:
    driver: bridge
    